package com.uacastplayer.core.security

import javax.crypto.SecretKeyFactory
import javax.crypto.spec.PBEKeySpec
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertThrows
import org.junit.Test

class Pbkdf2HmacSha256Test {
    // Independently cross-checked with OpenSSL (Node crypto.pbkdf2Sync), not generated by this fallback.
    @Test fun `matches independent vectors at one two and 4096 iterations`() {
        val expected = mapOf(
            1 to "120fb6cffcf8b32c43e7225256c4f837a86548c92ccc35480805987cb70be17b",
            2 to "ae4d0c95af6b46d32d0adff928f06dd02a303f8ef3c251dfd6e2d85a95474c43",
            4096 to "c5e478d59288c841aa530db6845c4c8d962893a001ce4e11a4963873aa98134a",
        )
        expected.forEach { (iterations, hash) ->
            assertEquals(hash, derive("password", "salt", iterations))
        }
    }

    @Test fun `empty password preserves native HMAC semantics`() {
        assertEquals("62384466264daadc4144018c6bd864648272b34da8980d31521ffcce92ae003b", derive("", "salt", 2))
    }

    @Test fun `password and salt use UTF8 without changing their contents`() {
        assertEquals("fdaa5cc1fff92a05de7a64bd79b5941bc55a5ca7f90d54f5e7f2472395dd0f50", derive("пароль", "сіль", 2))
    }

    @Test fun `production work factor matches existing native persisted hashes`() {
        val salt = "fixed-salt".toByteArray(Charsets.UTF_8)
        val expected = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256")
            .generateSecret(PBEKeySpec("1234".toCharArray(), salt, 120_000, 256)).encoded
        assertArrayEquals(expected, Pbkdf2HmacSha256.derive("1234", salt, 120_000))
        assertEquals(
            "95c156af00455b2003522250f315f732fb5e28590ee253e259fb78054312aa78",
            derive("1234", "fixed-salt", 120_000),
        )
        assertArrayEquals("fixed-salt".toByteArray(Charsets.UTF_8), salt)
    }

    @Test fun `nonpositive work factor is rejected`() {
        listOf(0, -1).forEach { iterations ->
            assertThrows(IllegalArgumentException::class.java) { derive("1234", "salt", iterations) }
        }
    }

    private fun derive(password: String, salt: String, iterations: Int): String =
        Pbkdf2HmacSha256.derive(password, salt.toByteArray(Charsets.UTF_8), iterations)
            .joinToString("") { "%02x".format(it) }
}
